### ISSUE TITLE
starting to document planning logic

### ISSUE THREAD

**Issue by bhaugen** [valueflows/vf-apps-planning#1]
I'm going through the NRP code and my memories of planning in several previous projects to surface issues and quirks that might be interesting and/or useful for ValueFlows. I'll write up these in separate comments in this thread as I find or remember them. The order will be random.

Some of the techniques and terms will be from [Material Requirements Planning (MRP)](https://en.wikipedia.org/wiki/Material_requirements_planning), [Capacity Requirements Planning (CRP)](https://en.wikipedia.org/wiki/Capacity_planning), and [Finite Capacity Scheduling (FCS)](https://www.ifm.eng.cam.ac.uk/research/dstools/finite-capacity-scheduling/).

Many of the topics below will be sub-topics of [dependent demand explosions](https://valueflo.ws/appendix/dependent-demand.html). "Explosion" means to generate a process to satisfy the demand, guided by a recipe, which will generate dependent demands for the inputs to the process, which then may also need to be exploded, recursively until all generated demands are satisfied or no additional information can be found about how to satisfy a demand.

The stories and techniques will be examples from past practice but not necessarily what a vf-planning app should do. However, a vf-planning app would most likely encounter all of these problems and quirks.

**Comment by bhaugen** [comment]
**Netting** is the first stage of attempting to satisfy a demand. What resources are already available to satisfy it? Maybe we don't need to do anything but take those resources...
* If sufficient quantity is on hand and available to satisfy the demand, it does not need to be exploded. 
* Or if some lesser quantity is on hand and available, then only the remainder of the demand quantity needs to be exploded.
* Or if a process has been planned with more output than the existing demands (either because of a larger batch quantity or production-to-stock), then some or all of the extra output could satisfy this demand and the logic is the same as for onhand quantity. The output from a planned process is called "scheduled receipts" in MRP.

But if an onhand or scheduled receipt quantity has other existing demands, those need to be sequenced by priority to decide if this new demand can take some of it. If the total of the scheduled demands is less than the available quantity, the new demand can take the excess. But if not, the new demand must find its place in the priority sequence. If it is at the end, then the new demand can take what is left over, if any. 

The interesting issue arises when the new demand finds its place before the end of the priority sequence, which means its insertion will affect the demands that come after it.

This situation can be handled in more than one way.

Two of those ways are called "hard allocations" or "soft allocations".
* Hard allocations create commitments for each planned demand for a quantity of some onhand inventory or scheduled receipt. With hard allocations, the previously scheduled processes would not be bumped, and the new demand would need to be exploded to satisfy itself.
* Soft allocations do not create such commitments. The sequence of demands and available resources is always evaluated on request from the information existing at the time of the request, which might change later. With soft allocations, the new demand can be inserted into the priority sequence and bump the lower-priority demands down in the queue.

Every planning implementation where I was involved used soft allocations. The word from people who had experience with hard allocations are that they are trouble. They lock you into a situation where any change either requires following all the ripple effects and making dependent changes, or you can't satisfy an unexpected demand.

But soft allocations have their own ripple effects, like when the new demand gets inserted into the priority sequence and affects subsequent demands, maybe making one of them unsatisfied. In that case, some humans should be notified and given a chance to do something. More on that [later](https://github.com/valueflows/vf-apps-planning/issues/1#issuecomment-487310215)...

**Comment by bhaugen** [comment]
**Substitutable and non-substitutable resources**

A substitutable resource is one where every bit of the same Resource Classification or Specification is the same as every other bit. Like nails of the same size and type. Or grain or flour of the same composition. The plan to satisfy a demand only needs to find an available quantity.

Non-substitutable resources are unique individuals in some way. Like for a translation process, the source material, for example, a document or media resource. Or a shirt that is made to order to your measurements. One article or movie is not the same as another article or movie. So usually netting is not possible. The required resource must be the exact specified resource, or it must be created.

**Comment by bhaugen** [comment]
**Same resource as input and output of the same process**

This happens especially in processes of improvement or repair. The document is edited but is the same document. The bicycle is repaired but is the same bicycle.

ValueFlows provides the Actions _accept_ and _improve_ for such processes, where (for example) the bicycle is _accepted_ as an input to the repair process, and then as an output, is _improved_.

How can a computer identify a bicycle needing repair from a bicycle having been repaired? It could have the same resource id and tracking identifier in more than one recorded event. But a computer can tell if a bicycle has gone through the repair process.

But sometimes the same resource will go through more than one process. Now the identification becomes more complicated. 

We first ran into that situation with the [Guerilla Translators](https://www.guerrillatranslation.org/), whose workflow for a document goes through the processes Translate, Edit, Proofread, and Prepare for publication. They would like to be able to track documents that are at each of those process stages.

So we added a property called "stage" to the NRP equivalents of RecipeFlows, Commitments, EconomicEvents, and EconomicResources. "Stage" was a reference to a RecipeProcess, which was added to a resource when it came out of a process, and was also used in the recipe and planning for commitments.

Netting, for example, needs to consider the stage of a resource or scheduled receipt as well as the Resource Classification or Specification (as well as resource identity if it is not substitutable.)

Took us awhile to work through all the details of how to handle process flows like those translation ones. We had a long discussion, which was captured in this document called [Stream Resources](https://docs.google.com/document/d/1SpJuFv9JWzMcSQ_AvjBgiwCaK8G6pz6rqtN-C9iGmS8/edit?usp=sharing) because that was the name of an implementation of such process flows in the 1990's in a system called Prism which was the first commercial software that handled them. Bill McCarthy calls them "carrier resources".

**Comment by bhaugen** [comment]
**Reactive replanning, or the return of the demand priority shuffle**

Remember this pushy demand in the [netting topic](https://github.com/valueflows/vf-apps-planning/issues/1#issuecomment-487294617)?  
> when the new demand gets inserted into the priority sequence and affects subsequent demands, maybe making one of them unsatisfied. In that case, some humans should be notified and given a chance to do something. More on that later...

This is "later". 

Most plans become increasingly _wrong_  as events bump into them.

MRP is often run as a nightly batch job. As it encounters changes from what it thinks should happen, it will emit [Action Messages](https://docs.infor.com/help_m3kpd_15.1.2/index.jsp?topic=%2Fcom.lawson.help.scplanhs-uwa%2Fcrp0200.html) for a planner to look at and do something about. So in the case of a demand that got bumped to the end of the priority queue and no longer has any resources to statisfy it, So MRP might emit an Action Message to schedule a new production process to satisfy that orphaned demand, or increase the production quantity of a previously scheduled process.

MRP might emit hundreds of Action Messages. They get really tedious to wade through and take the required actions. So in two projects, we created a [event-condition-action](https://en.wikipedia.org/wiki/Event_condition_action) trouble-shooting feature something like [IfThisThenThat](https://en.wikipedia.org/wiki/IFTTT), where the action messages became interactive, and the planner was given a selection list of possible actions to take (like Schedule a new process or Increase the production quantity of this other process). And clicking the button executed the required changes.

The planner could also create a rule to do that same thing in the same or similar situations automatically.  Which could be dangerous, but would get the job done a lot faster the next times.

We triggered the event-condition-action loop on every change to previous plans, no nightly batch job with hundreds of action messages, so the plan was usually up-to-date most of the time.

It is also possible to automatically replan in some situations, or almost all the time, but every planner I have ever talked to wanted to be kept in the loop at least until they understand what would happen if they made an automatic rule. And they wanted to select the rules.

**Comment by bhaugen** [comment]
**How is everything in a plan connected?**

The purpose of dependent demand planning is to satisfy independent demands. 

From the [Dependent Demand Pattern](https://hillside.net/plop/plop97/Proceedings/haugen.pdf):
> **Definitions:**
**Independent Demand** is any demand that has no cause within the [operational]-system context (although it may have a cause in a larger context). For example, to an automobile dealer, a customer order for a new car is an independent demand (although to the customer, it might have been dependent on the unreliability of the customer’s old car).
**Dependent Demand** is any demand that is caused by an independent demand, or is necessary to the
satisfaction of the independent demand. For example, an independent demand for a new car causes
dependent demands for all of the components which make up the car.

So the planning process explodes each independent demand to generate the dependent demands and processes to satisfy it. Each independent demand and its exploded dependents form a tree. 

The various dependent demand trees in a plan might form directed graph shapes as multiple demands converge on the same onhand resources or scheduled receipts. So it's nice to be able to see which independent demands converged on what.

In previous projects, we kept the whole dependent demand tree for an independent demand marked with the independent demand they were generated to satisfy. This is easy to do computationally because the identity of the independent demand can be passed along to all of the explosion functions.

Thus, for example, if subsequent events delay a dependent process such that the due date for the independent demand might be affected, that can trigger an event-condition-action message for a planner and also notify the agents interested in the independent demand.

_I do not recommend that VF add an independent demand property on e.g. all of the dependent commitments now._ Wait until a real-life situation arises where it would be needed, or at least useful.

**Comment by bhaugen** [comment]
One other thing about **reactive replanning:** 

The software needs to know how everything in the plan is connected. VF should be able to provide that information, it's similar to [tracking and tracing](https://valueflo.ws/appendix/track.html), but in this case, following the ripple effects of a change.

**Comment by bhaugen** [comment]
### Types of recipes:

* **Manufacturing Recipes:** assemble or transform input resources into different output resources, for example:
    * Assemble a robot from metal, wires, computer chips, software, etc.
    * Bake bread from flour, yeast, water, etc., using an oven.
* **Workflow Recipes:** change the same resource into a different stage of the same resource, for example:
    * Translate a source document, edit the translation, format for publication, and publish.
    * Harvest, dry and garble (refine) batches of herbs.

See also https://speakerdeck.com/mikorizal/5-nrp-recipe-concepts-and-tutorial?slide=12

We've arbitrarily named these "manufacturing" and "workflow" recipes, but they might also be named "assemble from components" and "transform through stages", respectively.

**Comment by bhaugen** [comment]
### Forward or backward scheduling:

(Backward scheduling is often called "backscheduling" in MRP literature.)

Forward scheduling means scheduling into the "future" from a start date.

Backscheduling means scheduling into the "past" from an end date.

Both "future" and "past" mean "relative to the start or end date", not necessarily relative to today.

The different types of recipes have different capabilities for scheduling.

Workflow recipes can be forward or backward scheduled fairly simply, because they are basically linear flows, with a single beginning and a single end.

Manufacturing recipes can only be backscheduled simply (in one pass), because they have a single end, but branch into several possible beginnings,, which cannot be enumerated until they are generated, because they may be pruned by netting. 

So if you wanted to forward-schedule from a manufacturing recipe, you would need to first backschedule and then find the earliest start time, and forward schedule from that, and then find the other starting points and reschedule them forward if needed.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-apps-planning/-/issues/1.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
